import React, { useState, useEffect } from 'react';
import { Card, Btn, FormGroup, FormRow, Alert, Tag } from './UI';
import { getAllClasses, getSubjectsForClass, getCurriculumLevel, CURRICULUM_LEVELS } from '../data/initialData';
import { loadSchoolData } from '../supabase';

/* ══════════════════════════════════════════════════════════
   TEACHER SELF-REGISTRATION
   Accessed via invite link: ?school=SCHOOL_ID&action=register
   The link is generated by admin — it contains the school ID
   so the form can load classes and subjects automatically.
══════════════════════════════════════════════════════════ */
export function TeacherRegisterPage({ data: propData, setData, onBack }) {
  const [schoolData, setSchoolData] = useState(propData);
  const [loading,    setLoading]    = useState(false);
  const [step,       setStep]       = useState(1);
  const [form,       setForm]       = useState({
    name: '', email: '', phone: '', password: '', confirmPassword: '',
    staffType: 'teaching', dept: 'Academics',
    isClassTeacher: false, classTeacherOf: '',
  });
  const [subjectRows, setSubjectRows] = useState([{ subject: '', classes: [] }]);
  const [error,      setError]       = useState('');
  const [submitting, setSubmitting]  = useState(false);

  // Load school data from URL schoolId if not passed as prop
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const schoolId = params.get('school');
    if (schoolId && (!propData?._schoolId || propData._schoolId !== schoolId)) {
      setLoading(true);
      loadSchoolData(schoolId)
        .then(d => { if (d) setSchoolData(d); })
        .finally(() => setLoading(false));
    }
  }, []);

  const data = schoolData || propData || {};
  const allClasses  = getAllClasses(data);
  const depts = data.departments || ['Academics','Management','Kitchen','Sports','Library','Finance','Counselling','Security'];

  // Get subjects for a specific class (CBC/JSS aware)
  function getSubsForClass(cls) {
    return getSubjectsForClass(cls, data);
  }

  // All unique subjects across all classes teacher might teach
  function allSubjectsForSelectedClasses() {
    const selected = subjectRows.flatMap(r => r.classes);
    const unique = new Set(selected.flatMap(cls => getSubsForClass(cls)));
    return [...unique].sort();
  }

  function addSubjectRow() { setSubjectRows(r => [...r, { subject: '', classes: [] }]); }
  function removeSubjectRow(i) { setSubjectRows(r => r.filter((_, idx) => idx !== i)); }
  function updateRow(i, field, value) { setSubjectRows(r => r.map((row, idx) => idx === i ? { ...row, [field]: value } : row)); }
  function toggleClass(rowIdx, cls) {
    setSubjectRows(r => r.map((row, idx) => {
      if (idx !== rowIdx) return row;
      const classes = row.classes.includes(cls) ? row.classes.filter(c => c !== cls) : [...row.classes, cls];
      return { ...row, classes };
    }));
  }

  function validateStep1() {
    if (!form.name.trim())     return 'Full name is required.';
    if (!form.email.trim())    return 'Email is required.';
    if ((data.teachers || []).find(t => t.email?.toLowerCase() === form.email.trim().toLowerCase() && t.status !== 'pending'))
      return 'This email is already registered.';
    if (!form.password || form.password.length < 6) return 'Password must be at least 6 characters.';
    if (form.password !== form.confirmPassword)       return 'Passwords do not match.';
    return '';
  }

  function validateStep2() {
    if (form.staffType === 'teaching') {
      const valid = subjectRows.filter(r => r.subject && r.classes.length > 0);
      if (valid.length === 0) return 'Add at least one subject and select the classes you teach it in.';
      if (form.isClassTeacher && !form.classTeacherOf) return 'Select which class you are class teacher of.';
    }
    return '';
  }

  async function nextStep() {
    setError('');
    if (step === 1) {
      const err = validateStep1(); if (err) { setError(err); return; }
      setStep(2);
    } else if (step === 2) {
      const err = validateStep2(); if (err) { setError(err); return; }
      await submitRegistration();
    }
  }

  async function submitRegistration() {
    setSubmitting(true);
    const validSubjects = subjectRows.filter(r => r.subject && r.classes.length > 0);
    const staffId = 'P' + Date.now().toString().slice(-6);
    const cap = s => s ? s.trim().replace(/\b\w/g, c => c.toUpperCase()) : '';

    const pendingTeacher = {
      id:              Date.now(),
      name:            cap(form.name.trim()),
      email:           form.email.trim().toLowerCase(),
      phone:           form.phone.trim(),
      staffId,
      dept:            form.dept,
      staffType:       form.staffType,
      isClassTeacher:  form.isClassTeacher && form.staffType === 'teaching',
      classTeacherOf:  form.isClassTeacher ? form.classTeacherOf : null,
      subjects:        validSubjects,
      canSeeKitchenAlerts: false,
      canSeeFees:      false,
      admin:           false,
      password:        form.password,
      status:          'pending',
      registeredAt:    new Date().toISOString(),
    };

    setData(d => ({
      ...d,
      teachers: [...(d.teachers || []), pendingTeacher],
      notifications: [...(d.notifications || []), {
        id:      Date.now() + 1,
        to:      'ADMIN',
        from:    cap(form.name.trim()),
        message: `New teacher registration awaiting approval: ${cap(form.name.trim())} (${form.email}) — ${validSubjects.map(s => s.subject).join(', ')}`,
        date:    new Date().toISOString().split('T')[0],
        read:    false,
        type:    'teacher_registration',
        teacherId: pendingTeacher.id,
      }],
    }));
    setSubmitting(false);
    setStep(3);
  }

  if (loading) {
    return (
      <div style={{ minHeight:'100vh', background:'var(--bg)', display:'flex', alignItems:'center', justifyContent:'center' }}>
        <div style={{ color:'var(--text-sub)', fontSize:16 }}>Loading school information...</div>
      </div>
    );
  }

  if (step === 3) {
    return (
      <div style={{ minHeight:'100vh', background:'var(--bg)', display:'flex', alignItems:'center', justifyContent:'center', padding:20 }}>
        <div style={{ background:'var(--surface)', border:'1px solid #2a3350', borderRadius:16, padding:40, maxWidth:480, width:'100%', textAlign:'center' }}>
          <div style={{ fontSize:48, marginBottom:16 }}>✅</div>
          <div style={{ fontSize:22, fontWeight:800, color:'#10b981', marginBottom:12 }}>Registration Submitted!</div>
          <div style={{ fontSize:14, color:'var(--text-sub)', lineHeight:1.7, marginBottom:24 }}>
            Your registration has been sent to <strong style={{ color:'var(--text)' }}>{data.schoolName}</strong> administrator for approval.<br/><br/>
            You will be able to log in once your account is approved.
          </div>
          <Btn onClick={onBack} variant="ghost">← Back to Login</Btn>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight:'100vh', background:'var(--bg)', display:'flex', alignItems:'center', justifyContent:'center', padding:20 }}>
      <div style={{ background:'var(--surface)', border:'1px solid #2a3350', borderRadius:16, padding:32, maxWidth:600, width:'100%' }}>
        {/* Header */}
        <div style={{ textAlign:'center', marginBottom:24 }}>
          <div style={{ fontSize:30, marginBottom:6 }}>👩‍🏫</div>
          <div style={{ fontSize:20, fontWeight:800, color:'var(--text)' }}>Teacher Registration</div>
          <div style={{ fontSize:13, color:'#4f8ef7', marginTop:2 }}>{data.schoolName || 'School'}</div>
          {/* Steps */}
          <div style={{ display:'flex', justifyContent:'center', alignItems:'center', gap:8, marginTop:14 }}>
            {['Personal Details','Teaching Info'].map((label, i) => (
              <React.Fragment key={i}>
                <div style={{ display:'flex', alignItems:'center', gap:6 }}>
                  <div style={{ width:24, height:24, borderRadius:'50%', display:'flex', alignItems:'center', justifyContent:'center', fontSize:11, fontWeight:700, background: step > i+1 ? '#10b981' : step === i+1 ? '#4f8ef7' : 'var(--border)', color:'#fff' }}>
                    {step > i+1 ? '✓' : i+1}
                  </div>
                  <span style={{ fontSize:12, color: step === i+1 ? '#4f8ef7' : 'var(--text-muted)' }}>{label}</span>
                </div>
                {i < 1 && <span style={{ color:'var(--border)' }}>→</span>}
              </React.Fragment>
            ))}
          </div>
        </div>

        {error && <div style={{ background:'#ef444415', border:'1px solid #ef444440', color:'#ef4444', borderRadius:8, padding:'10px 14px', fontSize:13, marginBottom:16 }}>⚠ {error}</div>}

        {step === 1 && (
          <>
            <div style={{ fontSize:11, fontWeight:700, color:'#4f8ef7', textTransform:'uppercase', letterSpacing:1, marginBottom:12 }}>Personal Details</div>
            <FormGroup label="Full Name *">
              <input value={form.name} onChange={e => setForm({...form, name:e.target.value})} placeholder="e.g. Jane Wanjiku Mwangi" autoFocus />
            </FormGroup>
            <FormRow>
              <FormGroup label="Email Address *">
                <input type="email" value={form.email} onChange={e => setForm({...form, email:e.target.value})} placeholder="jane@email.com" />
              </FormGroup>
              <FormGroup label="Phone Number">
                <input value={form.phone} onChange={e => setForm({...form, phone:e.target.value})} placeholder="0712 345 678" />
              </FormGroup>
            </FormRow>
            <FormRow>
              <FormGroup label="Password *">
                <input type="password" value={form.password} onChange={e => setForm({...form, password:e.target.value})} placeholder="Min. 6 characters" />
              </FormGroup>
              <FormGroup label="Confirm Password *">
                <input type="password" value={form.confirmPassword} onChange={e => setForm({...form, confirmPassword:e.target.value})} placeholder="Repeat password" />
              </FormGroup>
            </FormRow>
            <FormRow>
              <FormGroup label="Department">
                <select value={form.dept} onChange={e => setForm({...form, dept:e.target.value})}>
                  {depts.map(d => <option key={d} value={d}>{d}</option>)}
                </select>
              </FormGroup>
              <FormGroup label="Staff Type">
                <select value={form.staffType} onChange={e => setForm({...form, staffType:e.target.value})}>
                  <option value="teaching">Teaching Staff</option>
                  <option value="non_teaching">Non-Teaching Staff</option>
                </select>
              </FormGroup>
            </FormRow>
          </>
        )}

        {step === 2 && (
          <>
            {form.staffType === 'teaching' ? (
              <>
                <div style={{ fontSize:11, fontWeight:700, color:'#4f8ef7', textTransform:'uppercase', letterSpacing:1, marginBottom:12 }}>Teaching Assignment</div>

                {/* Class teacher toggle */}
                <label style={{ display:'flex', alignItems:'center', gap:10, cursor:'pointer', fontSize:13, marginBottom:14, padding:'10px 14px', background:'var(--surface2)', borderRadius:8 }}>
                  <input type="checkbox" checked={form.isClassTeacher} onChange={e => setForm({...form, isClassTeacher:e.target.checked, classTeacherOf:''})} />
                  I am a class teacher (responsible for one specific class/stream)
                </label>
                {form.isClassTeacher && (
                  <FormGroup label="I am class teacher of">
                    <select value={form.classTeacherOf} onChange={e => setForm({...form, classTeacherOf:e.target.value})}>
                      <option value="">Select class...</option>
                      {allClasses.map(c => <option key={c} value={c}>{c}</option>)}
                    </select>
                  </FormGroup>
                )}

                <div style={{ fontSize:13, color:'var(--text-sub)', marginBottom:10 }}>
                  Add each subject you teach and select the classes you teach it in:
                </div>

                {subjectRows.map((row, i) => {
                  // Get available subjects based on selected classes
                  const availSubs = row.classes.length > 0
                    ? [...new Set(row.classes.flatMap(c => getSubsForClass(c)))].sort()
                    : allClasses.length > 0
                      ? [...new Set(allClasses.flatMap(c => getSubsForClass(c)))].sort()
                      : [];

                  return (
                    <div key={i} style={{ background:'var(--surface2)', borderRadius:10, padding:14, marginBottom:10, border:'1px solid #2a3350' }}>
                      <div style={{ display:'flex', gap:10, alignItems:'center', marginBottom:10 }}>
                        <div style={{ flex:1 }}>
                          <div style={{ fontSize:11, color:'var(--text-muted)', marginBottom:4 }}>Subject</div>
                          <select value={row.subject} onChange={e => updateRow(i, 'subject', e.target.value)} style={{ width:'100%' }}>
                            <option value="">Select subject...</option>
                            {availSubs.map(s => <option key={s} value={s}>{s}</option>)}
                          </select>
                        </div>
                        {subjectRows.length > 1 && (
                          <button onClick={() => removeSubjectRow(i)} style={{ background:'#ef444415', border:'1px solid #ef444440', color:'#ef4444', borderRadius:6, padding:'6px 12px', cursor:'pointer', fontSize:12, alignSelf:'flex-end' }}>Remove</button>
                        )}
                      </div>

                      <div style={{ fontSize:11, color:'var(--text-muted)', marginBottom:8 }}>
                        Classes I teach <strong>{row.subject || 'this subject'}</strong> in:
                      </div>

                      {/* Group classes by curriculum level */}
                      {Object.entries(CURRICULUM_LEVELS).map(([key, level]) => {
                        const levelClasses = allClasses.filter(c => level.classes.some(lc => c.toLowerCase().startsWith(lc.toLowerCase())));
                        if (levelClasses.length === 0) return null;
                        return (
                          <div key={key} style={{ marginBottom:8 }}>
                            <div style={{ fontSize:10, color:'#475569', fontWeight:700, textTransform:'uppercase', marginBottom:4 }}>{level.label}</div>
                            <div style={{ display:'flex', flexWrap:'wrap', gap:5 }}>
                              {levelClasses.map(c => (
                                <div key={c} onClick={() => toggleClass(i, c)} style={{
                                  padding:'4px 10px', borderRadius:6, fontSize:12, cursor:'pointer', fontWeight:500, userSelect:'none',
                                  background: row.classes.includes(c) ? '#4f8ef7' : 'var(--surface2)',
                                  color: row.classes.includes(c) ? '#fff' : 'var(--text-sub)',
                                  border: `1px solid ${row.classes.includes(c) ? '#4f8ef7' : 'var(--border)'}`,
                                }}>{c}</div>
                              ))}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  );
                })}
                <button onClick={addSubjectRow} style={{ background:'none', border:'1px dashed #2a3350', color:'var(--text-muted)', borderRadius:8, padding:'8px 16px', cursor:'pointer', fontSize:12, width:'100%', marginBottom:8 }}>
                  + Add Another Subject
                </button>
              </>
            ) : (
              <div style={{ padding:20, textAlign:'center', color:'var(--text-sub)' }}>
                <div style={{ fontSize:32, marginBottom:8 }}>🏢</div>
                <div>Non-Teaching Staff — no subject assignments needed.</div>
              </div>
            )}
          </>
        )}

        <div style={{ display:'flex', gap:10, justifyContent:'space-between', marginTop:20 }}>
          <Btn variant="ghost" onClick={step === 1 ? onBack : () => { setStep(step-1); setError(''); }}>
            {step === 1 ? '← Back to Login' : '← Back'}
          </Btn>
          <Btn onClick={nextStep} disabled={submitting}>
            {step === 2 ? (submitting ? 'Submitting...' : '✅ Submit Registration') : 'Next →'}
          </Btn>
        </div>
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════════════════
   PENDING TEACHER APPROVALS — shown in admin Teachers page
══════════════════════════════════════════════════════════ */
export function PendingTeacherApprovals({ data, setData }) {
  const pending = (data.teachers || []).filter(t => t.status === 'pending');
  if (pending.length === 0) return null;

  function approve(teacherId) {
    const newStaffId = 'T' + String(Date.now()).slice(-4);
    setData(d => ({
      ...d,
      teachers: (d.teachers||[]).map(t => t.id === teacherId ? { ...t, status:'active', staffId: newStaffId } : t),
    }));
  }
  function reject(teacherId) {
    if (!window.confirm('Reject and remove this teacher registration?')) return;
    setData(d => ({ ...d, teachers: (d.teachers||[]).filter(t => t.id !== teacherId) }));
  }

  return (
    <div style={{ background:'var(--surface)', border:'1px solid #f59e0b40', borderRadius:12, padding:16, marginBottom:20 }}>
      <div style={{ fontSize:14, fontWeight:700, color:'#f59e0b', marginBottom:4 }}>⏳ Pending Teacher Registrations ({pending.length})</div>
      <div style={{ fontSize:12, color:'var(--text-muted)', marginBottom:12 }}>These teachers registered and are waiting for your approval before they can log in.</div>
      {pending.map(t => (
        <div key={t.id} style={{ background:'var(--surface2)', borderRadius:10, padding:14, marginBottom:10, border:'1px solid #f59e0b30' }}>
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', flexWrap:'wrap', gap:10 }}>
            <div>
              <div style={{ fontSize:14, fontWeight:700, color:'var(--text)' }}>{t.name}</div>
              <div style={{ fontSize:12, color:'var(--text-muted)', marginTop:2 }}>{t.email} {t.phone && `· ${t.phone}`} · {t.dept}</div>
              {t.isClassTeacher && <div style={{ fontSize:11, color:'#10b981', marginTop:4 }}>Class Teacher of: {t.classTeacherOf}</div>}
              {(t.subjects||[]).length > 0 && (
                <div style={{ display:'flex', flexWrap:'wrap', gap:5, marginTop:8 }}>
                  {t.subjects.map((s, i) => (
                    <span key={i} style={{ background:'#4f8ef710', border:'1px solid #4f8ef730', borderRadius:5, padding:'2px 8px', fontSize:11, color:'#4f8ef7' }}>
                      {s.subject}: {(s.classes||[]).join(', ')}
                    </span>
                  ))}
                </div>
              )}
              <div style={{ fontSize:10, color:'#475569', marginTop:6 }}>Registered: {new Date(t.registeredAt).toLocaleDateString('en-KE')}</div>
            </div>
            <div style={{ display:'flex', gap:8 }}>
              <Btn variant="success" size="sm" onClick={() => approve(t.id)}>✅ Approve</Btn>
              <Btn variant="danger"  size="sm" onClick={() => reject(t.id)}>❌ Reject</Btn>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

/* ══════════════════════════════════════════════════════════
   INVITE LINK GENERATOR — shown in admin Teachers page
══════════════════════════════════════════════════════════ */
export function InviteLinkGenerator({ data }) {
  const [copied, setCopied] = useState(false);
  const baseUrl = window.location.origin + window.location.pathname;
  const link = `${baseUrl}?school=${data._schoolId}&action=register`;

  function copy() {
    navigator.clipboard.writeText(link).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  return (
    <div style={{ background:'var(--surface2)', border:'1px solid #4f8ef730', borderRadius:10, padding:16, marginBottom:20 }}>
      <div style={{ fontSize:13, fontWeight:600, color:'#4f8ef7', marginBottom:4 }}>🔗 Teacher Self-Registration Link</div>
      <div style={{ fontSize:12, color:'var(--text-muted)', marginBottom:10 }}>
        Share this link with your teachers. When they open it, they will see your school's classes grouped by level (Lower Primary, Upper Primary, JSS etc.) and can select exactly which classes and subjects they teach. You will get a notification to approve them.
      </div>
      <div style={{ display:'flex', gap:8, alignItems:'center', flexWrap:'wrap' }}>
        <input readOnly value={link} style={{ flex:1, minWidth:200, fontSize:11, fontFamily:'monospace', color:'var(--text-sub)', background:'var(--bg)', border:'1px solid #2a3350', borderRadius:6, padding:'8px 10px' }} />
        <Btn variant="ghost" size="sm" onClick={copy}>{copied ? '✅ Copied!' : '📋 Copy Link'}</Btn>
      </div>
    </div>
  );
}
